tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "microsoft/git"
brew "readline"
brew "asdf"
brew "bat"
brew "chezmoi"
brew "cocoapods"
brew "exa"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"
brew "git"
brew "git-secrets"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "gnupg"
brew "go"
brew "shared-mime-info"
brew "libheif"
brew "python@3.8"
brew "imagemagick"
brew "jq"
brew "lua"
brew "mas"
brew "mysql"
brew "mysql@5.6"
brew "neovim"
brew "node", link: false
brew "node-build"
brew "nodebrew"
brew "openssl@3"
brew "peco"
brew "pyenv"
brew "redis"
brew "ruby-build"
brew "starship"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
cask "flutter"
cask "font-3270-nerd-font"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "git-credential-manager-core"
cask "zoom"
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
