shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"